---

sudo: required

services:
  - docker

before_install:
  - docker pull solita/ubuntu-systemd
  - make bin/python

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
